version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "08:00"
      timezone: America/Los_Angeles
    exclude-paths:
      - .github/workflows/release.yml
    open-pull-requests-limit: 5
